theme: jekyll-theme-cayman

title: "Project"
locale: "de"
name: "Taras Lazariv"

description: "EasyBuild easyconfigs"
url: "https://lazariv.github.io/easybuild-easyconfigs/"
repository: "easybuild-easyconfigs"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
google_analytics: UA-156051452-1

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false